spring:
  #邮箱配置
  mail:
    host: smtp.xiongdi.cn
    username: cx_admin@xiongdi.cn
    #QQ邮箱的授权码
    password: xd123456
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
    port: 25
  #freemarker配置
  freemarker:
    content-type: text/html
    #后缀名
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
  # Active Profile Settings




#设置一个邮件发送人
lance:
  mail:
    sender: cx_admin@xiongdi.cn